# Generated by Django 6.1 on 2026-09-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('centro_tutorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='academico.centrotutorial')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='academico.periodoacademico')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='academico.programaacademico')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='academico.semestre')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['centro_tutorial__nombre', 'programa__nombre', 'semestre__numero', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_academicas', to='academico.asignatura')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_academicas', to='academico.modalidad')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_academicas', to='academico.periodoacademico')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_academicas', to='academico.profesor')),
            ],
            options={
                'verbose_name': 'Oferta Académica',
                'verbose_name_plural': 'Ofertas Académicas',
                'ordering': ['periodo__nombre', 'asignatura__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='academico.aula')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='horarios.ofertaacademica')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='OfertaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupos', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_grupo', to='horarios.grupo')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_grupo', to='horarios.ofertaacademica')),
            ],
            options={
                'verbose_name': 'Grupo de Oferta Académica',
                'verbose_name_plural': 'Grupos de Oferta Académica',
                'ordering': ['grupo__programa__nombre', 'grupo__semestre__numero', 'grupo__codigo'],
            },
        ),
        migrations.AddField(
            model_name='ofertaacademica',
            name='grupos',
            field=models.ManyToManyField(related_name='ofertas_academicas', through='horarios.OfertaGrupo', to='horarios.grupo'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('centro_tutorial', 'periodo', 'programa', 'semestre', 'codigo'), name='uq_grupo_contexto_codigo'),
        ),
        migrations.AddConstraint(
            model_name='ofertagrupo',
            constraint=models.UniqueConstraint(fields=('oferta', 'grupo'), name='uq_oferta_grupo'),
        ),
    ]
