# Generated by Django 6.1 on 2026-08-30 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aula')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodoacademico')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.profesor')),
            ],
        ),
    ]
