# Generated by Django 6.1 on 2026-09-01 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área Académica',
                'verbose_name_plural': 'Áreas Académicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CentroTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro Tutorial',
                'verbose_name_plural': 'Centros Tutoriales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X')], unique=True)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_academicos', to='academico.facultad')),
            ],
            options={
                'verbose_name': 'Programa Académico',
                'verbose_name_plural': 'Programas Académicos',
                'ordering': ['facultad__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaCentroTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('centro_tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_academicos', to='academico.centrotutorial')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_tutoriales', to='academico.programaacademico')),
            ],
            options={
                'verbose_name': 'Programa por Centro Tutorial',
                'verbose_name_plural': 'Programas por Centro Tutorial',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('centro_tutorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sedes', to='academico.centrotutorial')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['centro_tutorial__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('FISICA', 'Física'), ('VIRTUAL', 'Virtual')], default='FISICA', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='academico.sede')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['sede__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudioAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('area_academica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='academico.areaacademica')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='academico.asignatura')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_estudio', to='academico.programaacademico')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='academico.semestre')),
            ],
            options={
                'verbose_name': 'Asignatura del Plan de Estudio',
                'verbose_name_plural': 'Asignaturas del Plan de Estudio',
                'ordering': ['programa__nombre', 'semestre__numero', 'asignatura__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='programaacademico',
            constraint=models.UniqueConstraint(fields=('facultad', 'nombre'), name='uq_programa_facultad_nombre'),
        ),
        migrations.AddConstraint(
            model_name='programacentrotutorial',
            constraint=models.UniqueConstraint(fields=('programa', 'centro_tutorial'), name='uq_programa_centro_tutorial'),
        ),
        migrations.AddConstraint(
            model_name='sede',
            constraint=models.UniqueConstraint(fields=('centro_tutorial', 'codigo'), name='uq_sede_centro_codigo'),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(fields=('sede', 'codigo'), name='uq_aula_sede_codigo'),
        ),
        migrations.AddConstraint(
            model_name='planestudioasignatura',
            constraint=models.UniqueConstraint(fields=('programa', 'asignatura', 'semestre'), name='uq_plan_programa_asignatura_semestre'),
        ),
    ]
